---
namespace: copilot-metrics-viewer
project: alist-corporate-it
env: corporate-it
cpu_limit: 1000m
mem_limit: 1Gi
replica_count: 2
iap_enabled: true

# nodeSelector
web_type: e2
web_size: small
web_preemptible: true
